### ISSUE TITLE
Datasette publish executable issue

### ISSUE THREAD

**Issue by Poiuy7312** [AstuteSource/chasten#117]
This is a very similar bug as #51 for the datasette-publish command this only an issue on windows

**To Reproduce**
Simply run the datasette-publish command on a windows OS and it won't be able to find the executable for datasette

**Expected behavior**
This shouldn't happen it should be able to find the executable this is an issue because of windows storing executables in a different way than Linux and Mac

**Comment by gkapfham** [comment]
Hello @Poiuy7312, yes, I agree that this is an issue! Do you agree that it is connected to the fact that it is not finding the executable in the virtual environment due to a path issue? If it something different, could you please give me an update on what you think is the key problem and how to solve it?

**Comment by Poiuy7312** [comment]
> Hello @Poiuy7312, yes, I agree that this is an issue! Do you agree that it is connected to the fact that it is not finding the executable in the virtual environment due to a path issue? If it something different, could you please give me an update on what you think is the key problem and how to solve it?

I believe it's the same as issue #51 and the fix should be pretty simple as it should just require sending the start_datasette_server function the OS of the computer when using the publish command
