### ISSUE TITLE
Provide a Sub-Command for the Output of Version Information

### ISSUE THREAD

**Issue by gkapfham** [AstuteSource/chasten#12]
Right now it is not possible for a person who uses `chasten` to see what
version of the program that they have installed. This means that there should
be a command like `chasten version` that should display version information of
the tool itself and, potentially, the version of key packages used by `chasten`.

**Comment by gkapfham** [comment]
FIXME: add griffin

**Comment by CalebKendra** [comment]
Trying to base fix off of: https://github.com/tiangolo/typer/issues/52

**Comment by CalebKendra** [comment]
> The latest updates related to this issue can be found in the '[version_command](https://github.com/AstuteSource/chasten/tree/version_command)' branch
> 
> **Implemented Features and Improvements**
> 
> 1. 'version' Sub-Command Implementation: This implementation allows for obtaining the Chasten version by running `chasten version`
> 2. Improvements to 'util.get_chasten_version()' Function: The updated version includes a fallback mechanism using 'pkg_resources' to retrieve the Chasten version if 'importlib_metadata' fails due to the package not being fully installed in certain environments like 'poetry shell' or 'poetry run'. The combination of both 'importlib. metadata' and 'pkg_resources' ensures more reliable version retrieval in various scenarios. It covers cases where 'importlib. metadata' may not work.
> 
> **Thoughts**: I'm also considering implementing a message "Package version not available" to give users more information as to why version retrieval fails, other than simply returning the default version.
> 
> I would appreciate your suggestions to improve my code. @CalebKendra @gkapfham

Your solution on the `version_command` branch looks good to me, I like the implementation you built better then my own since your version gives a typer "command" and mine gives a typer "option", this leads to less bugs as this way `chasten` is not confused when you give it no "command" but just the `--version` option.

This also avoids the confusion you would get when using the `--version` option on another command such as `configure` as we only want to give the PyPi version of `chasten`.

I am going to add a few formating bits but besides that I like it.
