### ISSUE TITLE
Installing Chasten for MacOS

### ISSUE THREAD

**Issue by rodriguez03** [AstuteSource/chasten#44]
We could write in the issues that here are several ways to install chasten. Anyone is welcome to contribute more ways

```
pip failed to build package:
    pysqlite3

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    src/connection.c:1385:10: error: implicit declaration of function 'sqlite3_enable_load_extension' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    src/connection.c:1409:10: error: implicit declaration of function 'sqlite3_load_extension' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    error: command '/usr/bin/clang' failed with exit code 1
```

or another error looks like:

```
failed to building wheels for pysqlite3
```

**Comment by gkapfham** [comment]
Briefly, here are some points to consider in regards to this issue:
- If possible, I would like to avoid the manual creation of virtual environments or the installation of dependencies with `pip`, at least when we are developing the tool ourselves. This means that, as developers, we should stick to using `poetry`.
- With that said, it is perfectly valid for you to raise an issue connected to the installation of the tool with either `pipx` or `pip`
- While I appreciate that this issue is specifically about MacOS we need to be absolutely sure that the suggestion works for all operating systems.

**Comment by gkapfham** [comment]
What is the status of this issue @Jaclynpqc and @rodriguez03?

**Comment by boulais01** [comment]
Is this resolved with the recent merging of pysqlite3-removal-test-branch?

**Comment by rodriguez03** [comment]
Most of our colleagues with Mac OS have gotten chasten to work
